import { getLineProfile, pushTextMessage, switchRichMenu } from "@/lib/line";
import type { ResolvedLineAccount } from "@/lib/line-accounts";
import { logger } from "@/lib/logger";
import type { createAdminSupabaseClient } from "@/lib/supabase/server";

type SupabaseAdmin = ReturnType<typeof createAdminSupabaseClient>;

export function endUserNicknameFromLineId(lineUserId: string): string {
  return `ユーザー_${lineUserId.slice(-6)}`;
}

export function isAutoGeneratedNickname(nickname: string): boolean {
  return nickname.startsWith("ユーザー_");
}

const LINE_PROFILE_SYNC_INTERVAL_MS = 1000 * 60 * 60 * 24;

/** 未契約ユーザー向け welcome + リッチメニュー（follow / 初回 message 共通） */
export async function sendLineUncontractedOnboarding(
  account: ResolvedLineAccount,
  lineUserId: string,
  welcomeMessage: string
): Promise<void> {
  await pushTextMessage(account.credentials, lineUserId, welcomeMessage);

  const richMenuId = account.richMenuUncontractedId;
  if (richMenuId) {
    try {
      await switchRichMenu(account.credentials, lineUserId, richMenuId);
    } catch (err) {
      logger.error("LINE uncontracted rich menu switch failed", {
        lineUserId,
        error: err instanceof Error ? err.message : "unknown",
      });
    }
  }
}

/**
 * incomplete ユーザーを取得または作成（line_user_id ユニーク競合を吸収）
 */
export async function ensureIncompleteEndUser(
  supabase: SupabaseAdmin,
  lineUserId: string,
  planCode: string
): Promise<{
  id: string;
  isNew: boolean;
  nickname: string;
  lineProfileSyncedAt: string | null;
}> {
  const { data: existing } = await supabase
    .from("end_users")
    .select("id, nickname, line_profile_synced_at")
    .eq("line_user_id", lineUserId)
    .maybeSingle();

  if (existing) {
    return {
      id: existing.id,
      isNew: false,
      nickname: existing.nickname,
      lineProfileSyncedAt: existing.line_profile_synced_at,
    };
  }

  const { data: created, error } = await supabase
    .from("end_users")
    .insert({
      line_user_id: lineUserId,
      nickname: endUserNicknameFromLineId(lineUserId),
      status: "incomplete",
      plan_code: planCode,
    })
    .select("id, nickname, line_profile_synced_at")
    .single();

  if (!error && created) {
    return {
      id: created.id,
      isNew: true,
      nickname: created.nickname,
      lineProfileSyncedAt: created.line_profile_synced_at,
    };
  }

  if (error?.code === "23505") {
    const { data: raced } = await supabase
      .from("end_users")
      .select("id, nickname, line_profile_synced_at")
      .eq("line_user_id", lineUserId)
      .single();
    if (raced) {
      return {
        id: raced.id,
        isNew: false,
        nickname: raced.nickname,
        lineProfileSyncedAt: raced.line_profile_synced_at,
      };
    }
  }

  throw new Error(`Failed to ensure end_user: ${error?.message ?? "unknown"}`);
}

/**
 * LINEプロフィールを end_users に同期
 * - nicknameが自動生成値のときのみ displayName で置き換える
 * - 既に最近同期している場合はスキップできる
 */
export async function syncLineProfileToEndUser(
  supabase: SupabaseAdmin,
  account: ResolvedLineAccount,
  params: {
    endUserId: string;
    lineUserId: string;
    nickname: string;
    lastSyncedAt: string | null;
    force?: boolean;
  }
): Promise<void> {
  const { endUserId, lineUserId, nickname, lastSyncedAt, force = false } = params;

  if (!force && lastSyncedAt) {
    const elapsed = Date.now() - new Date(lastSyncedAt).getTime();
    if (elapsed < LINE_PROFILE_SYNC_INTERVAL_MS) {
      return;
    }
  }

  try {
    const profile = await getLineProfile(account.credentials, lineUserId);
    const updates: {
      line_display_name: string;
      line_picture_url: string | null;
      line_profile_synced_at: string;
      nickname?: string;
    } = {
      line_display_name: profile.displayName,
      line_picture_url: profile.pictureUrl,
      line_profile_synced_at: new Date().toISOString(),
    };

    if (isAutoGeneratedNickname(nickname)) {
      updates.nickname = profile.displayName;
    }

    const { error } = await supabase
      .from("end_users")
      .update(updates)
      .eq("id", endUserId);

    if (error) {
      throw new Error(`Failed to update end_user profile: ${error.message}`);
    }
  } catch (err) {
    logger.warn("LINE profile sync failed", {
      endUserId,
      lineUserId,
      error: err instanceof Error ? err.message : "unknown",
    });
  }
}
