import { getLineProfile, pushTextMessage, switchRichMenu } from "@/lib/line";
import type { ResolvedLineAccount } from "@/lib/line-accounts";
import { logger } from "@/lib/logger";
import type { createAdminSupabaseClient } from "@/lib/supabase/server";

type SupabaseAdmin = ReturnType<typeof createAdminSupabaseClient>;

export function endUserNicknameFromLineId(lineUserId: string): string {
  return `ユーザー_${lineUserId.slice(-6)}`;
}

export function isAutoGeneratedNickname(nickname: string): boolean {
  return nickname.startsWith("ユーザー_");
}

const LINE_PROFILE_SYNC_INTERVAL_MS = 1000 * 60 * 60 * 24;

/** 未契約ユーザー向け welcome + リッチメニュー（follow / 初回 message 共通） */
export async function sendLineUncontractedOnboarding(
  account: ResolvedLineAccount,
  lineUserId: string,
  welcomeMessage: string
): Promise<void> {
  await pushTextMessage(account.credentials, lineUserId, welcomeMessage);

  const richMenuId = account.richMenuUncontractedId;
  if (richMenuId) {
    try {
      await switchRichMenu(account.credentials, lineUserId, richMenuId);
    } catch (err) {
      logger.error("LINE uncontracted rich menu switch failed", {
        lineUserId,
        error: err instanceof Error ? err.message : "unknown",
      });
    }
  }
}

// ensureIncompleteEndUser は削除した。
// UID だけで `.maybeSingle()` して1行に決め打ちする実装で、複数メイト契約により
// 同じUIDに関係行が複数できると「エラーで落ちる」か「別メイトの行を取り違える」。
// 着地先の解決は lib/person.ts の ensureInboundRelationship（受信アカウントのメイトで解決）に一本化した。
export async function syncLineProfileToEndUser(
  supabase: SupabaseAdmin,
  account: ResolvedLineAccount,
  params: {
    endUserId: string;
    lineUserId: string;
    nickname: string;
    lastSyncedAt: string | null;
    force?: boolean;
  }
): Promise<void> {
  const { endUserId, lineUserId, nickname, lastSyncedAt, force = false } = params;

  if (!force && lastSyncedAt) {
    const elapsed = Date.now() - new Date(lastSyncedAt).getTime();
    if (elapsed < LINE_PROFILE_SYNC_INTERVAL_MS) {
      return;
    }
  }

  try {
    const profile = await getLineProfile(account.credentials, lineUserId);
    const updates: {
      line_display_name: string;
      line_picture_url: string | null;
      line_profile_synced_at: string;
      nickname?: string;
    } = {
      line_display_name: profile.displayName,
      line_picture_url: profile.pictureUrl,
      line_profile_synced_at: new Date().toISOString(),
    };

    if (isAutoGeneratedNickname(nickname)) {
      updates.nickname = profile.displayName;
    }

    const { error } = await supabase
      .from("end_users")
      .update(updates)
      .eq("id", endUserId);

    if (error) {
      throw new Error(`Failed to update end_user profile: ${error.message}`);
    }
  } catch (err) {
    logger.warn("LINE profile sync failed", {
      endUserId,
      lineUserId,
      error: err instanceof Error ? err.message : "unknown",
    });
  }
}
