#!/usr/bin/env tsx

/**
 * 既存 end_users の LINE プロフィールを同期する。
 *
 * 使い方:
 *   npm run sync:line-profiles -- --dry-run   # 変更せず対象を表示
 *   npm run sync:line-profiles                # 未同期/仮名ユーザーを同期
 *   npm run sync:line-profiles -- --force     # 既に同期済みでも再取得
 *
 * 手動編集済みの nickname は上書きせず、LINE表示名は line_display_name に保存する。
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import { resolve } from "path";

dotenv.config({ path: resolve(__dirname, "../.env.local") });

type EndUserProfileTarget = {
  id: string;
  line_user_id: string;
  nickname: string;
  line_display_name: string | null;
  line_profile_synced_at: string | null;
};

type LineProfileResponse = {
  userId: string;
  displayName: string;
  pictureUrl?: string;
  statusMessage?: string;
};

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const LINE_CHANNEL_ACCESS_TOKEN = process.env.LINE_CHANNEL_ACCESS_TOKEN;

const DRY_RUN = process.argv.includes("--dry-run");
const FORCE = process.argv.includes("--force");
const LINE_API_BASE = "https://api.line.me/v2/bot";

function isAutoGeneratedNickname(nickname: string): boolean {
  return nickname.startsWith("ユーザー_");
}

async function fetchLineProfile(lineUserId: string): Promise<LineProfileResponse> {
  const response = await fetch(
    `${LINE_API_BASE}/profile/${encodeURIComponent(lineUserId)}`,
    {
      headers: {
        Authorization: `Bearer ${LINE_CHANNEL_ACCESS_TOKEN}`,
      },
    }
  );

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`LINE profile fetch failed: ${response.status} ${body.slice(0, 160)}`);
  }

  return (await response.json()) as LineProfileResponse;
}

async function main() {
  if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
    console.error("Supabase の URL / SERVICE_ROLE_KEY が設定されていません");
    process.exit(1);
  }
  if (!LINE_CHANNEL_ACCESS_TOKEN) {
    console.error("LINE_CHANNEL_ACCESS_TOKEN が設定されていません");
    process.exit(1);
  }

  const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });

  console.log(
    `${DRY_RUN ? "[dry-run] " : ""}LINEプロフィール同期を開始します...${FORCE ? " (force)" : ""}\n`
  );

  let query = supabase
    .from("end_users")
    .select("id, line_user_id, nickname, line_display_name, line_profile_synced_at")
    .not("line_user_id", "is", null)
    .order("created_at", { ascending: true });

  if (!FORCE) {
    query = query.or("line_display_name.is.null,nickname.like.ユーザー_%");
  }

  const { data: users, error } = await query;

  if (error) {
    console.error("end_users の取得に失敗:", error.message);
    process.exit(1);
  }

  const targets = (users ?? []) as EndUserProfileTarget[];
  console.log(`同期対象: ${targets.length} 件\n`);

  let updated = 0;
  let skipped = 0;
  let failed = 0;

  for (const user of targets) {
    try {
      const profile = await fetchLineProfile(user.line_user_id);
      const shouldUpdateNickname = isAutoGeneratedNickname(user.nickname);
      const updates: {
        line_display_name: string;
        line_picture_url: string | null;
        line_profile_synced_at: string;
        nickname?: string;
      } = {
        line_display_name: profile.displayName,
        line_picture_url: profile.pictureUrl ?? null,
        line_profile_synced_at: new Date().toISOString(),
      };

      if (shouldUpdateNickname) {
        updates.nickname = profile.displayName;
      }

      if (DRY_RUN) {
        console.log(
          `- would update end_user=${user.id} line_display_name=${profile.displayName}${
            shouldUpdateNickname ? " nicknameも更新" : ""
          }`
        );
        updated++;
        continue;
      }

      const { error: updateError } = await supabase
        .from("end_users")
        .update(updates)
        .eq("id", user.id);

      if (updateError) {
        console.log(`- fail  end_user=${user.id} (${updateError.message})`);
        failed++;
        continue;
      }

      console.log(
        `- update end_user=${user.id} line_display_name=${profile.displayName}${
          shouldUpdateNickname ? " nicknameも更新" : ""
        }`
      );
      updated++;
    } catch (err) {
      console.log(`- fail  end_user=${user.id} (${(err as Error).message})`);
      failed++;
    }
  }

  console.log(`\n完了: 更新 ${updated} / スキップ ${skipped} / 失敗 ${failed}`);

  if (failed > 0) {
    process.exit(1);
  }
}

main();
