"use server";

import { createServerSupabaseClient } from "@/lib/supabase/server";
import { getCurrentStaff } from "@/lib/auth";
import { Result } from "./types";
import type { SubscriptionStatus } from "@/lib/supabase/types";
import {
  calculateSlaRemaining,
  isUnreported,
  calculateInboxPriority,
  hasSentMessageToday,
} from "@/lib/calculations";

export type InboxItem = {
  id: string;
  nickname: string;
  displayName: string;
  lineDisplayName: string | null;
  linePictureUrl: string | null;
  planCode: "light" | "standard" | "premium";
  status: "trial" | "active" | "past_due" | "paused" | "canceled" | "incomplete";
  assignedCastId: string | null;
  assignedCastName: string | null;
  lineAccountName: string | null;
  tags: string[];
  priorityScore: number;
  hasRisk: boolean;
  riskLevel: number | null;
  lastUserMessageAt: string | null;
  lastCastMessageAt: string | null;
  unrepliedMinutes: number | null;
  slaRemainingMinutes: number | null;
  slaWarningMinutes: number;
  isUnreported: boolean;
  lastCheckinDate: string | null;
  birthday: string | null;
  isBirthdayToday: boolean;
  // 新しいフィールド
  hasUnrepliedMessage: boolean;
  hasSentTodayMessage: boolean;
  todaySentCount: number;
  replyStatus: "unreplied" | "not_sent_today" | "replied";
  lastMessageBody: string | null;
  lastMessageDirection: "in" | "out" | null;
  lastMessageAt: string | null;
  unreadCount: number;
  hasUnread: boolean;
};

export type InboxFilters = {
  planCodes?: string[];
  statuses?: string[];
  assignedCastId?: string;
  hasRisk?: boolean;
  isUnreported?: boolean;
  replyStatus?: "unreplied" | "not_sent_today" | "all";
  hasUnassigned?: boolean;
  slaStatus?: "breached" | "warning" | "all";
  excludePaused?: boolean;
  todaySentZero?: boolean;
  query?: string;
  tags?: string[];
  sortBy?: "priority" | "last_message" | "nickname" | "unreplied_duration" | "today_sent_asc" | "last_reply_oldest";
};

export type GetInboxItemsInput = {
  filters?: InboxFilters;
};

export type InboxSummary = {
  total: number;
  unreplied: number;
  notSentToday: number;
  replied: number;
};

export type GetInboxItemsResult = Result<{
  items: InboxItem[];
  summary: InboxSummary;
  availableTags: string[];
}>;

// プラン別SLA設定
const planSlaConfig = {
  light: { slaMinutes: 1440, warningMinutes: 240 },
  standard: { slaMinutes: 720, warningMinutes: 120 },
  premium: { slaMinutes: 120, warningMinutes: 30 },
};

// ヘルパー関数: メッセージをユーザーIDごとにグループ化
function groupByUserId<T extends { end_user_id: string }>(
  items: T[]
): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const existing = map.get(item.end_user_id);
    if (existing) {
      existing.push(item);
    } else {
      map.set(item.end_user_id, [item]);
    }
  }
  return map;
}

function isAutoGeneratedNickname(nickname: string): boolean {
  return nickname.startsWith("ユーザー_");
}

function resolveDisplayName(nickname: string, lineDisplayName: string | null): string {
  if (isAutoGeneratedNickname(nickname) && lineDisplayName) {
    return lineDisplayName;
  }
  return nickname;
}

/**
 * Inbox一覧取得（最適化版）
 * 権限: Admin/Supervisor全件、Cast担当のみ
 * 
 * パフォーマンス改善:
 * - 一括クエリでメッセージ、チェックイン、リスクフラグを取得
 * - N+1問題を解消
 */
export async function getInboxItems(
  input: GetInboxItemsInput = {}
): Promise<GetInboxItemsResult> {
  const staff = await getCurrentStaff();
  if (!staff) {
    return {
      ok: false,
      error: { code: "UNAUTHORIZED", message: "ログインが必要です" },
    };
  }

  const supabase = await createServerSupabaseClient();
  const { filters } = input;

  // ユーザー一覧取得（RLSで自動フィルタ）
  let query = supabase
    .from("end_users")
    .select(`
      id,
      nickname,
      plan_code,
      status,
      assigned_cast_id,
      tags,
      birthday,
      line_display_name,
      line_picture_url,
      paused_priority_penalty,
      created_at,
      staff_profiles!end_users_assigned_cast_id_fkey (
        display_name
      ),
      line_official_accounts!end_users_primary_line_account_id_fkey (
        name
      )
    `);

  // ステータス絞り込み:
  // - 状態フィルタを明示選択した場合はそれを尊重（解約済みのみ抽出＝復帰アプローチ用も可）
  // - 未選択（既定）は「サービス提供中」のみ表示し、未契約(incomplete)・解約済み(canceled)は除外
  if (filters?.statuses?.length) {
    query = query.in("status", filters.statuses as SubscriptionStatus[]);
  } else {
    query = query.not("status", "in", '("incomplete","canceled")');
  }

  // フィルタ適用
  if (filters?.planCodes?.length) {
    query = query.in("plan_code", filters.planCodes);
  }
  if (filters?.assignedCastId) {
    query = query.eq("assigned_cast_id", filters.assignedCastId);
  }
  if (filters?.hasUnassigned) {
    query = query.is("assigned_cast_id", null);
  }
  if (filters?.query?.trim()) {
    // ニックネーム部分一致検索（%・_ をエスケープ）
    const escaped = filters.query.trim().replace(/[%_]/g, (m) => `\\${m}`);
    query = query.or(
      `nickname.ilike.%${escaped}%,line_display_name.ilike.%${escaped}%`
    );
  }

  const { data: users, error: usersError } = await query;

  if (usersError) {
    return {
      ok: false,
      error: { code: "UNKNOWN", message: "データの取得に失敗しました" },
    };
  }

  if (!users || users.length === 0) {
    return {
      ok: true,
      data: {
        items: [],
        summary: { total: 0, unreplied: 0, notSentToday: 0, replied: 0 },
        availableTags: [],
      },
    };
  }

  const now = new Date();
  const todayJst = now.toLocaleDateString("sv-SE", { timeZone: "Asia/Tokyo" });
  const todayStart = new Date(todayJst + "T00:00:00+09:00");

  const userIds = users.map((u) => u.id);

  // ===== 一括クエリで関連データを取得（互いに独立 → 並列実行） =====
  // メッセージは全件転送せず、DB側で per-user 要約（最新メッセージ・最終受信/送信・
  // 未読数）に集計する RPC を使う（転送量とJS処理を大幅削減）。既読状態も RPC 内で解決。
  const [
    { data: threadSummaries },
    { data: todayMessages },
    { data: allCheckins },
    { data: allRiskFlags },
    { data: allHistoricalRisks },
  ] = await Promise.all([
    // スレッド要約（最新メッセージ／最終受信・送信時刻／未読数）
    supabase.rpc("inbox_thread_summary", { p_user_ids: userIds, p_staff_id: staff.id }),
    // 今日のメイト送信メッセージ
    supabase
      .from("messages")
      .select("end_user_id")
      .in("end_user_id", userIds)
      .eq("direction", "out")
      .gte("created_at", todayStart.toISOString()),
    // 全チェックイン
    supabase
      .from("checkins")
      .select("end_user_id, date")
      .in("end_user_id", userIds)
      .order("date", { ascending: false }),
    // 全リスクフラグ（openのみ）
    supabase
      .from("risk_flags")
      .select("end_user_id, risk_level")
      .in("end_user_id", userIds)
      .eq("status", "open")
      .order("created_at", { ascending: false }),
    // 過去にリスクフラグが立ったことのあるユーザー
    supabase
      .from("risk_flags")
      .select("end_user_id")
      .in("end_user_id", userIds)
      .in("status", ["resolved", "ack"]),
  ]);

  const previousRiskUserIds = new Set(
    (allHistoricalRisks ?? []).map((r) => r.end_user_id)
  );
  const summaryMap = new Map(
    (threadSummaries ?? []).map((s) => [s.end_user_id, s])
  );

  // ===== データをユーザーIDでグループ化 =====

  const checkinsMap = groupByUserId(
    (allCheckins ?? []).map((c) => ({ ...c, end_user_id: c.end_user_id }))
  );
  const riskFlagsMap = groupByUserId(
    (allRiskFlags ?? []).map((r) => ({ ...r, end_user_id: r.end_user_id }))
  );
  
  // 今日の送信数をカウント
  const todaySentCountMap = new Map<string, number>();
  (todayMessages ?? []).forEach((m) => {
    todaySentCountMap.set(m.end_user_id, (todaySentCountMap.get(m.end_user_id) ?? 0) + 1);
  });

  // ===== 各ユーザーのデータを処理 =====
  
  const items: InboxItem[] = users.map((user) => {
    const summary = summaryMap.get(user.id) ?? null;
    const userCheckins = checkinsMap.get(user.id) ?? [];
    const userRiskFlags = riskFlagsMap.get(user.id) ?? [];

    // メッセージ由来の値は DB 集計（RPC）から取得する。
    const lastInboundAt = summary?.last_inbound_at ?? null; // 最終の受信メッセージ時刻
    const lastOutboundAt = summary?.last_outbound_at ?? null; // 最終のメイト返信時刻
    // 最後のチェックイン
    const lastCheckin = userCheckins[0];
    // リスクフラグ
    const riskFlag = userRiskFlags[0];

    const unreadCount = summary?.unread_count ?? 0;

    const planCode = user.plan_code as "light" | "standard" | "premium";
    const slaConfig = planSlaConfig[planCode] ?? planSlaConfig.standard;

    // 未返信判定・時間計算
    let unrepliedMinutes: number | null = null;
    let slaRemainingMinutes: number | null = null;
    let hasUnrepliedMessage = false;

    if (lastInboundAt) {
      const lastMsgTime = new Date(lastInboundAt);
      const lastReplyTime = lastOutboundAt ? new Date(lastOutboundAt) : null;

      // 最後のユーザーメッセージが最後の返信より新しい場合、未返信
      if (!lastReplyTime || lastMsgTime > lastReplyTime) {
        hasUnrepliedMessage = true;
        unrepliedMinutes = Math.floor(
          (now.getTime() - lastMsgTime.getTime()) / (1000 * 60)
        );
        slaRemainingMinutes = calculateSlaRemaining(
          lastMsgTime,
          slaConfig.slaMinutes,
          now
        );
      }
    }

    // 今日送信したかどうか
    const lastReplyTime = lastOutboundAt ? new Date(lastOutboundAt) : null;
    const sentTodayMessage = hasSentMessageToday(lastReplyTime, now);

    // 返信状態を決定
    let replyStatus: InboxItem["replyStatus"];
    if (hasUnrepliedMessage) {
      replyStatus = "unreplied";
    } else if (!sentTodayMessage) {
      replyStatus = "not_sent_today";
    } else {
      replyStatus = "replied";
    }

    // 未報告判定
    const lastCheckinDate = lastCheckin?.date
      ? new Date(lastCheckin.date + "T00:00:00")
      : null;
    const lastMessageDate = lastInboundAt ? new Date(lastInboundAt) : null;
    const unreported = isUnreported(lastCheckinDate, lastMessageDate, 2, now);

    // 誕生日判定
    const birthday = user.birthday;
    let isBirthdayToday = false;
    if (birthday) {
      const birthdayMd = birthday.slice(5); // MM-DD
      const todayMd = todayJst.slice(5);
      isBirthdayToday = birthdayMd === todayMd;
    }

    // ユーザー作成日からの日数
    const createdAt = (user as unknown as { created_at: string }).created_at;
    const daysSinceCreation = createdAt
      ? Math.floor((now.getTime() - new Date(createdAt).getTime()) / (1000 * 60 * 60 * 24))
      : undefined;

    // 未報告日数
    let unreportedDays: number | undefined;
    if (unreported) {
      const latestContact = [
        lastCheckinDate ? lastCheckinDate.getTime() : 0,
        lastMessageDate ? lastMessageDate.getTime() : 0,
      ];
      const lastContactTime = Math.max(...latestContact);
      if (lastContactTime > 0) {
        unreportedDays = Math.floor((now.getTime() - lastContactTime) / (1000 * 60 * 60 * 24));
      }
    }

    // 優先度スコア計算（改善版）
    const priorityScore = calculateInboxPriority({
      hasRisk: !!riskFlag,
      slaRemainingMinutes,
      slaWarningMinutes: slaConfig.warningMinutes,
      isUnreported: unreported,
      isPaused: user.status === "paused",
      planPriorityLevel:
        planCode === "premium" ? 1 : planCode === "standard" ? 2 : 3,
      hasUnrepliedMessage,
      hasSentTodayMessage: sentTodayMessage,
      lastMessageTimestamp: lastInboundAt
        ? new Date(lastInboundAt).getTime()
        : undefined,
      isTrial: user.status === "trial",
      daysSinceCreation,
      unreportedDays,
      hadPreviousRisk: previousRiskUserIds.has(user.id),
    });

    const staffProfile = user.staff_profiles as unknown as { display_name: string } | null;
    const lineAccount = user.line_official_accounts as unknown as { name: string } | null;

    return {
      id: user.id,
      nickname: user.nickname,
      displayName: resolveDisplayName(user.nickname, user.line_display_name),
      lineDisplayName: user.line_display_name,
      linePictureUrl: user.line_picture_url,
      planCode,
      status: user.status as InboxItem["status"],
      assignedCastId: user.assigned_cast_id,
      assignedCastName: staffProfile?.display_name ?? null,
      lineAccountName: lineAccount?.name ?? null,
      tags: user.tags ?? [],
      priorityScore,
      hasRisk: !!riskFlag,
      riskLevel: riskFlag?.risk_level ?? null,
      lastUserMessageAt: lastInboundAt,
      lastCastMessageAt: lastOutboundAt,
      unrepliedMinutes,
      slaRemainingMinutes,
      slaWarningMinutes: slaConfig.warningMinutes,
      isUnreported: unreported,
      lastCheckinDate: lastCheckin?.date ?? null,
      birthday,
      isBirthdayToday,
      // 新しいフィールド
      hasUnrepliedMessage,
      hasSentTodayMessage: sentTodayMessage,
      todaySentCount: todaySentCountMap.get(user.id) ?? 0,
      replyStatus,
      lastMessageBody: summary?.last_message_body ?? null,
      lastMessageDirection: (summary?.last_message_direction as "in" | "out" | null) ?? null,
      lastMessageAt: summary?.last_message_at ?? null,
      unreadCount,
      hasUnread: unreadCount > 0,
    };
  });

  // サマリー計算
  const summary: InboxSummary = {
    total: items.length,
    unreplied: items.filter((i) => i.replyStatus === "unreplied").length,
    notSentToday: items.filter((i) => i.replyStatus === "not_sent_today").length,
    replied: items.filter((i) => i.replyStatus === "replied").length,
  };

  // タグ絞り込み用の候補（タグフィルタ適用前の全件から集約）
  const availableTags = Array.from(
    new Set(items.flatMap((item) => item.tags))
  ).sort((a, b) => a.localeCompare(b, "ja"));

  // フィルタ（クライアント側）
  let filteredItems = items;
  
  // 返信状態フィルタ
  if (filters?.replyStatus && filters.replyStatus !== "all") {
    if (filters.replyStatus === "unreplied") {
      filteredItems = filteredItems.filter((item) => item.hasUnrepliedMessage);
    } else if (filters.replyStatus === "not_sent_today") {
      filteredItems = filteredItems.filter(
        (item) => !item.hasUnrepliedMessage && !item.hasSentTodayMessage
      );
    }
  }
  
  if (filters?.hasRisk) {
    filteredItems = filteredItems.filter((item) => item.hasRisk);
  }
  if (filters?.isUnreported) {
    filteredItems = filteredItems.filter((item) => item.isUnreported);
  }

  // SLAフィルタ
  if (filters?.slaStatus && filters.slaStatus !== "all") {
    if (filters.slaStatus === "breached") {
      filteredItems = filteredItems.filter(
        (item) => item.slaRemainingMinutes !== null && item.slaRemainingMinutes === 0
      );
    } else if (filters.slaStatus === "warning") {
      filteredItems = filteredItems.filter(
        (item) =>
          item.slaRemainingMinutes !== null &&
          item.slaRemainingMinutes > 0 &&
          item.slaRemainingMinutes <= item.slaWarningMinutes
      );
    }
  }

  // 休止ユーザー除外
  if (filters?.excludePaused) {
    filteredItems = filteredItems.filter((item) => item.status !== "paused");
  }

  // 今日0回対応フィルタ
  if (filters?.todaySentZero) {
    filteredItems = filteredItems.filter((item) => item.todaySentCount === 0);
  }

  // タグ絞り込み（指定タグをすべて含むユーザーのみ）
  if (filters?.tags?.length) {
    const requiredTags = filters.tags;
    filteredItems = filteredItems.filter((item) =>
      requiredTags.every((tag) => item.tags.includes(tag))
    );
  }

  // ソート
  const sortBy = filters?.sortBy ?? "priority";
  if (sortBy === "priority") {
    filteredItems.sort((a, b) => b.priorityScore - a.priorityScore);
  } else if (sortBy === "last_message") {
    filteredItems.sort((a, b) => {
      const aTime = a.lastMessageAt ? new Date(a.lastMessageAt).getTime() : 0;
      const bTime = b.lastMessageAt ? new Date(b.lastMessageAt).getTime() : 0;
      return bTime - aTime;
    });
  } else if (sortBy === "nickname") {
    filteredItems.sort((a, b) => a.nickname.localeCompare(b.nickname, "ja"));
  } else if (sortBy === "unreplied_duration") {
    filteredItems.sort((a, b) => (b.unrepliedMinutes ?? -1) - (a.unrepliedMinutes ?? -1));
  } else if (sortBy === "today_sent_asc") {
    filteredItems.sort((a, b) => a.todaySentCount - b.todaySentCount);
  } else if (sortBy === "last_reply_oldest") {
    filteredItems.sort((a, b) => {
      const aTime = a.lastCastMessageAt ? new Date(a.lastCastMessageAt).getTime() : 0;
      const bTime = b.lastCastMessageAt ? new Date(b.lastCastMessageAt).getTime() : 0;
      return aTime - bTime;
    });
  }

  return { ok: true, data: { items: filteredItems, summary, availableTags } };
}
